### ISSUE TITLE
ImportError: cannot import name 'escape_fts' from 'utils'

### ISSUE THREAD

**Issue by YMan84** [astrowonk/search_transcripts#7]
I'm trying to test out your project in hopes of doing the same thing you did with a podcast's transcriptions but keep running into the following error and have not been able to figure out how to fix it:

```
Traceback (most recent call last):
  File "/home/yuriy/Syncthing/Git/Transcripts/test.py", line 1, in <module>
    from utils import escape_fts
ImportError: cannot import name 'escape_fts' from 'utils' (/home/yuriy/Syncthing/Git/Transcripts/my-venv/lib/python3.11/site-packages/utils/__init__.py)

```

I'm testing the script in an Arch Linux install, and every resource i've managed to find says that `escape_fts` should be in the utils library, but i cannot for the life of me understand why it's not working for me. 

If you have any input i'd be super grateful. Thanks!

**Comment by astrowonk** [comment]
Hello! Thanks for trying out my little library. Can you give some more details of what's in your `Test.py`?  Did you install search_transcripts with a `pip install .`?

I think the`.toml` file is set up poorly. 

Can you uninstall (`pip uninstall search_transcripts`) and then try installing from the branch `better-toml?` If that works for you, I'll merge to main.

**Comment by astrowonk** [comment]
I also think that I never put in the README to install with `pip install .` so that may be a problem in and of itself.

**Comment by astrowonk** [comment]
@YMan84  This new structure has to be better than the default so I merged. Try `pip install .` after pulling main. Then I think it should import properly.
